modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/ChocoCraft4"
license="MIT"

[[mods]]
modId="chococraft"
version="${file.jarVersion}"
displayName="Chococraft 4"
displayURL="https://www.curseforge.com/minecraft/mc-mods/chococraft"
authors="Mrbysco, Xalcon, Slayer5934, balika011"
credits="Thanks to EddieV for the original Chococraft, ArnoSaxena(Torojimas) and clienthax for maintaining it"
description='''
Chocobos in Minecraft
'''
[[dependencies.chococraft]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"